### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ArturGamerHD58** [wolfieboy09/KubeJS-TFMG#1]
Help pls

![image](https://github.com/user-attachments/assets/d298fcbb-bd8c-4ba5-83ee-1af8f983e427)

**Comment by wolfieboy09** [comment]
Logs please?

**Comment by wolfieboy09** [comment]
Also what's the mod version

**Comment by ArturGamerHD58** [comment]
Here, the version is 1.0.3, i can load the version 1.0.2 fine 
[log.txt](https://github.com/user-attachments/files/18054249/log.txt)

**Comment by wolfieboy09** [comment]
what, no, don't close

**Comment by ArturGamerHD58** [comment]
Sorry, the version was **1.0.2!!!** I mispelled 3

**Comment by wolfieboy09** [comment]
Version 1.0.3 is not a thing...

So, does the failing version `1.0.2` and `1.0.1` work? (for clarification)

**Comment by ArturGamerHD58** [comment]
yes

**Comment by wolfieboy09** [comment]
Okay, I found the cause just now
